### ISSUE TITLE
client的命令行参数是什么？

### ISSUE THREAD

**Issue by luckypoem** [asche910/flynet#1]
hi.

在mac上。
cd $GOPATH
go get -u -v github.com/asche910/SocketsProxy/client/

在$GOBIN/里面生成了可执行文件client,但是运行：client
显示：Client start: 

那么client的命令行参数是什么？

**Comment by asche910** [comment]
这个我还暂未处理命令行参数，不过过几天应该会出具体使用方法吧-------- Original message --------From: luckypoem <notifications@github.com>Date: Mon, Sep 30, 2019, 16:27To: asche910/SocketsProxy <SocketsProxy@noreply.github.com>Cc: Subscribed <subscribed@noreply.github.com>Subject: [asche910/SocketsProxy] client的命令行参数是什么？ (#1)hi.

在mac上。

cd $GOPATH

go get -u -v github.com/asche910/SocketsProxy/client/

在$GOBIN/里面生成了可执行文件client,但是运行：client

显示：Client start:

那么client的命令行参数是什么？

**Comment by asche910** [comment]
已更新README
