### ISSUE TITLE
加密协议可以自定义吗？

### ISSUE THREAD

**Issue by wdlid** [asche910/flynet#3]

**Comment by asche910** [comment]
目前版本暂不支持，不过后续版本会考虑的

**Comment by asche910** [comment]
已添加些常用的加密方法
['aes-128-cfb','aes-192-cfb', 'aes-256-cfb', 'aes-128-ctr', 'aes-192-ctr', 'aes-256-ctr', 'rc4-md5','rc4-md5-6', 'chacha20', 'chacha20-ietf']
加上```-m method```可使用对应的方法。由于时间关系暂时方法有点少，后续会补充上
