### ISSUE TITLE
SOCKS5的UDP有歧义?

### ISSUE THREAD

**Issue by leviathan0992** [asche910/flynet#4]
SOCKS5本身是支持UDP转发的，flynet代码我没有仔细看，项目指的UDP应该是使用KCP(UDP)转发TCP流量?

**Comment by asche910** [comment]
socks5自身支持udp没错，但项目中的kcp转发tcp可以实现全程通过udp进行，这样就可以借助53端口实现校园网或公共热点免认证上网。而且chrome等浏览器并不支持socsks5的udp协议。

**Comment by leviathan0992** [comment]
我理解，只是README写的容易让人误解是支持SOCKS5的UDP转发。
