### ISSUE TITLE
这个flynet程序翻不了墙啊

### ISSUE THREAD

**Issue by luckypoem** [asche910/flynet#5]
hi.

我在服务器端和本地机器上都设好了。虽然访问显示ip的网站，确实是显示我的vps的IP，但是访问不了blogspot.com, dongtaiwang.com等网站。为什么？

**Comment by asche910** [comment]
release里的版本， 建立的tcp连接目前是处于裸奔状态。其实数据做个简单的移位都可以通过GFW，鉴于刚发布时还没确定软件定位，所以没太在意加密方面的。抱歉了，所以最近正在做加密方面的，过几天应该就行了。

**Comment by asche910** [comment]
已更新，目前默认已添加加密。日本的vps测试可以正常访问， 按照这里的[socks5-tcp](https://github.com/asche910/flynet#cs%E6%A8%A1%E5%BC%8F%E7%9A%84socks5%E4%BB%A3%E7%90%86-tcp)  即可。不过还没有发布新的版本，使用的话需要手动编译下

**Comment by luckypoem** [comment]
我已经测试。
不过不稳定，使用半个小时后，就断开了。2边产生很多的EOF提示。

**Comment by asche910** [comment]
断开连接的问题最新的commit应该解决了。EOF准确说不能算错误吧，只是到达了文件末尾，我下次再处理下这里。

**Comment by luckypoem** [comment]
你最新的commit之后，我重新build,但是发现情况反而更糟糕，运行客户端命令不到10分钟，就断开连接了

**Comment by asche910** [comment]
已经发布了新版本，目前测试了一天也未出现断开连接的现象了

**Comment by briteming** [comment]
我还是翻墙失败。
我是按下文操作的，难道下面文章哪里错了吗？

“登陆linux vps.首先安装go环境。然后，

cd $GOPATH

go get -u -v github.com/asche910/flynet/cmd/server/

which server

/root/go/gopath/bin/server

mv /root/go/gopath/bin/server /root/go/gopath/bin/flynet-server
cd ~

flynet-server -h
flynet-server -M socks5-tcp -L 7777 -m aes-256-cfb --password mypassword
此命令是运行在前台的，可以利用systemd把它运行为service:
nano /etc/systemd/system/flynet.service
其内容为：
[Unit]
After=network.target

[Service]
ExecStart=/root/go/gopath/bin/flynet-server -M socks5-tcp -L 7777 -m aes-256-cfb --password mypassword
Restart=always

[Install]
WantedBy=multi-user.target

然后，运行：
systemctl start flynet
systemctl enable flynet
服务器端搭建完成。

在本地机器mac上。首先安装go环境。然后，
cd $GOPATH
go get -u -v github.com/asche910/flynet/cmd/client/
which client
$GOBIN/client
mv $GOBIN/client $GOBIN/flynet-client
cd ~
flynet-client -h
flynet-client -M socks5-tcp -L 8848 -m aes-256-cfb --password mypassword -S my-vps-ip:7777
保持此terminal不要关闭。设置本地机器的浏览器的socks5代理服务器为127.0.0.1 ，端口为8848 ，浏览器即可翻墙。

有点不稳定。如果翻墙失败，请重新运行客户端命令。”

**Comment by asche910** [comment]
@briteming   建议直接[这里下载](https://github.com/asche910/flynet/releases)编译好的版本，然后
服务端
```
server-flynet -M socks5-tcp -L port 
```
**或者** 这样来后台运行
```
server-flynet -M socks5-tcp -L port &
```
客户端
```
client-flynet -M socks5-tcp -L 8848 -S serverAddr:port
```
serverAddr和port分别替换成服务器地址和服务器端口即可

**Comment by briteming** [comment]
哦，我知道原因了。原因是画蛇添足的在服务器端的命令和客户端的命令中添加了：-m aes-256-cfb --password my-password

在服务器端的命令和客户端的命令中,去掉上面的参数，就可以成功利用flynet翻墙了。

**Comment by xclw2000** [comment]
按楼上的方法试了，还是翻不了墙，不知道什么原因，请帮我看一下
![image](https://user-images.githubusercontent.com/32091566/77398694-f80f2500-6de2-11ea-9f9d-9d584752072a.png)

![image](https://user-images.githubusercontent.com/32091566/77398760-107f3f80-6de3-11ea-81c9-35b526d3ba50.png)

![image](https://user-images.githubusercontent.com/32091566/77398810-2260e280-6de3-11ea-957f-2e97c9111f8f.png)

**Comment by asche910** [comment]
@xclw2000  命令行中出现进一步的请求信息才能说明使用到了代理。另外线路比较差的机子可能也连接不上。

**Comment by xclw2000** [comment]
> @xclw2000 命令行中出现进一步的请求信息才能说明使用到了代理。另外线路比较差的机子可能也连接不上。

进一步的请求信息是什么意思？是指在客户端还是服务端？
浏览器访问google的时候，我的客户端如出如下信息
2020/03/24 16:17:51 client accepted!
2020/03/24 16:17:51 client accepted!
2020/03/24 16:18:10 client accepted!
2020/03/24 16:18:26 client accepted!
2020/03/24 16:18:28 client accepted!
2020/03/24 16:18:30 client accepted!
2020/03/24 16:18:32 client accepted!

但服务端一直是waiting....
好像两边根本没有建立通讯，是我哪里配置错了吗？难道仅仅是线路的问题？
我用XShell连服务器，觉得速度还可以呀，也没出现频繁掉线的情况。
![image](https://user-images.githubusercontent.com/32091566/77403790-bd5dba80-6deb-11ea-982b-496169b03e66.png)

**Comment by xclw2000** [comment]
对了，我客户端的命令行参数里，连接server用的是IP地址，不是域名，因为我也不知道我这个服务器的域名是啥。会是这个的原因吗？我看例子里用的都是域名

**Comment by xclw2000** [comment]
![image](https://user-images.githubusercontent.com/32091566/77404323-84721580-6dec-11ea-8da3-56d5a7de4cea.png)

**Comment by asche910** [comment]
@xclw2000  应该是没有连到服务器，看下端口开放没

**Comment by xclw2000** [comment]
> @xclw2000 应该是没有连到服务器，看下端口开放没

![image](https://user-images.githubusercontent.com/32091566/77405903-cdc36480-6dee-11ea-8c95-b7bef108809d.png)

经telnet测试，ip和端口都没问题，是通的

**Comment by xclw2000** [comment]
我知道了，我设置的代理不对，我换了Firefox，设置了代理
![image](https://user-images.githubusercontent.com/32091566/77453220-ef920b00-6e31-11ea-8080-1f62c63879f8.png)
再次访问google,这次两边都有提示了，但是访问网页很长时间也没返回结果，最后提示超时。总之就是没能成功访问
![image](https://user-images.githubusercontent.com/32091566/77453416-3253e300-6e32-11ea-9716-886c3c6db474.png)
这是什么原因呢

**Comment by asche910** [comment]
那估计是gfw又升级了吧，我的使用效果也大不如前了。以后有空我再改改
