### ISSUE TITLE
C/S mode of Socks5 proxy by UDP可以拿来解决dns污染问题吗？

### ISSUE THREAD

**Issue by luckypoem** [asche910/flynet#7]
如何让“server -M socks5-udp -L 53”去连接8.8.8.8:53?

**Comment by asche910** [comment]
还未处理dns污染相关的问题，“server -M socks5-udp -L 53”只是以udp方式传输所有流量。后面有时间我再研究看看

**Comment by golden777** [comment]
> 还未处理dns污染相关的问题，“server -M socks5-udp -L 53”只是以udp方式传输所有流量。后面有时间我再研究看看
试用了一下,感觉有些卡卡的,超时,是不是 MTU过大?
另外能不能增加一个只在服务器上单独的UDP透明转发? UDP透明,不是简单的UDP转发,找了好久没有简单的. 其实只要非53端口的DNS请求就不会被污染, 所以服务器随便开个比如 5300端口转发到任意DNS服务器上,返回的DNS结果就是干净的,但是返回的CDN结果会以服务器IP为准,常常国内视频服务器解析到国外服务器上. 如果是UDP透明转发,DNS就会根据用户真实所在地IP解析CDN结果.

**Comment by asche910** [comment]
dns污染，通过pac的方式可以解决大部分的污染的问题，少数不在pac列表内的，可以手动添加到pac内。pac模式已经支持，另外HTTP代理全局应该也是能解决的，所以项目下一步应该会添加HTTP的代理。
